'use client';
import { MathText } from './MathText';
import { useEffect, useRef, useState } from 'react';
import { skills, domainNames } from '@/data/curriculum';
import { assessments } from '@/data/assessments';
import { topics, courseGroups, getQuestion } from '@/data/foundations';
import { fmt } from '@/data/foundations/types';
import { useMasteryStore } from '@/lib/store';
import { skillStatus, defaultState } from '@/lib/mastery';
import { placementEvidence, skillTestItems } from '@/lib/placement';
import { bankProgress, bankPlacementItems, nextBankRecord, parseNumeric, gradeNumeric, type BankRecords } from '@/lib/problem-bank';
import { loadBankRecords, saveBankRecord } from '@/lib/problem-bank-db';
import type { AssessmentItem } from '@/lib/types';

const button='rounded-xl border px-4 py-3 text-sm font-semibold disabled:opacity-30';
export function PlacementTests({onOpenLesson,onOpenFoundation}:{onOpenLesson:(id:string)=>void;onOpenFoundation:(id:string)=>void}){
  const [tab,setTab]=useState<'skills'|'foundations'>('foundations');
  return <div className="space-y-5"><section className="panel p-6"><h2 className="text-xl font-bold">できるところは、テストで飛ばす</h2><p className="mt-3 text-sm leading-7">最初から教材を読む必要はありません。分野や単元を選んで確認し、合格したノードを埋めます。後の誤答は該当箇所を再確認に戻します。時間を空けた定着確認は別に続けられます。</p><div className="mt-4 flex flex-wrap gap-2"><button className={button} aria-pressed={tab==='foundations'} onClick={()=>setTab('foundations')}>数学・力学など100単元</button><button className={button} aria-pressed={tab==='skills'} onClick={()=>setTab('skills')}>FRC・工学78スキル</button></div></section>{tab==='foundations'?<BankPlacement onOpen={onOpenFoundation}/>:<SkillPlacement onOpen={onOpenLesson}/>}</div>;
}
function SkillPlacement({onOpen}:{onOpen:(id:string)=>void}){
  const {states,assessmentHistory}=useMasteryStore();
  const [domain,setDomain]=useState('all'),[skill,setSkill]=useState('all'),[retest,setRetest]=useState(false);
  const [ids,setIds]=useState<string[]|null>(null),[index,setIndex]=useState(0);
  const list=skills.filter(s=>(domain==='all'||s.domain===domain)&&(skill==='all'||s.id===skill));
  const start=()=>{const chosen=list.filter(s=>retest||skillStatus(states[s.id]??defaultState())!=='mastered').slice(0,3);setIds(chosen.flatMap(s=>skillTestItems(s.id,assessmentHistory,retest).map(q=>q.id)));setIndex(0);};
  const item=assessments.find(a=>a.id===ids?.[index]);
  return <div className="space-y-4"><section className="panel p-5"><p className="text-sm leading-7">各スキルで異なる4問・2種類以上の能力を確認します。合格するとスキルマップが埋まり、スコアは90以上になります。誤答・「わからない」はテスト合格を取り消し、達成度を75以下へ戻します。実践課題の提出は別です。</p>
    {!ids&&<><div className="mt-4 flex flex-wrap gap-3"><select aria-label="スキルテストの分野" value={domain} onChange={e=>{setDomain(e.target.value);setSkill('all');}} className="max-w-full rounded-xl border p-3"><option value="all">全分野</option>{Object.entries(domainNames).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select><select aria-label="スキルテストの対象" value={skill} onChange={e=>setSkill(e.target.value)} className="max-w-full rounded-xl border p-3"><option value="all">未確認から最大3スキル</option>{skills.filter(s=>domain==='all'||s.domain===domain).map(s=><option key={s.id} value={s.id}>{s.nameJa}</option>)}</select></div><label className="mt-3 block text-sm"><input type="checkbox" checked={retest} onChange={e=>setRetest(e.target.checked)}/> 合格済みも再テストする</label><button className={`${button} mt-4 bg-[#0d1833] text-white`} onClick={start}>現在地テストを始める</button></>}
  </section>{ids&&(item?<SkillQuestion key={`${index}-${item.id}`} item={item} onNext={()=>setIndex(i=>i+1)} onOpen={onOpen}/>:<section className="panel p-5"><h3 className="font-bold">{ids.length?'テスト結果を反映しました。':'対象の未確認問題がありません。'}</h3><p className="mt-2 text-sm">合格済みの再テストや別の分野を選べます。</p><button className={`${button} mt-3`} onClick={()=>setIds(null)}>対象を選び直す</button></section>)}
  {ids&&item&&<button className={button} onClick={()=>setIds(null)}>中断する（回答済みの結果は保存）</button>}
  <div className="grid gap-3 md:grid-cols-3">{list.map(s=>{const st=states[s.id]??defaultState(),passed=skillStatus(st)==='mastered',ev=placementEvidence(s.id,assessmentHistory);return <section key={s.id} className={`rounded-xl border p-4 ${passed?'border-green-500 bg-green-50':'bg-white'}`}><h3 className="font-bold text-sm">{passed?'✓ ':''}{s.nameJa}</h3><p className="mt-2 text-xs">{Math.round(st.score)}% · {st.testPassed?'テストで確認済み':passed?'定着確認済み':'確認中'} · 異なる正答 {Math.min(ev.count,4)}/4</p><button className="mt-3 text-xs text-[#0857a2]" onClick={()=>onOpen(`eng-${s.id}`)}>必要な教材へ</button></section>})}</div></div>;
}
function SkillQuestion({item,onNext,onOpen}:{item:AssessmentItem;onNext:()=>void;onOpen:(id:string)=>void}){
  const answerAssessment=useMasteryStore(s=>s.answerAssessment);
  const [choice,setChoice]=useState<number|null>(null),[answer,setAnswer]=useState(''),[result,setResult]=useState<string|null>(null);
  const locked=useRef(false);
  const submit=(skip=false)=>{if(locked.current)return;locked.current=true;const n=parseNumeric(answer);const correct=item.format==='mcq'?choice===item.answer:n!==undefined&&Math.abs(n-Number(item.answer))<=(item.tolerance??0);const outcome=skip?'skipped':correct?'correct':'wrong';answerAssessment(item,outcome,'placement',{selectedAnswer:item.format==='mcq'?choice??undefined:answer});setResult(outcome);};
  return <section className="panel p-6"><div className="kicker">{skills.find(s=>s.id===item.skillId)?.nameJa} · L{item.difficulty} · {item.competency}</div><h3 className="mt-3 font-bold leading-8"><MathText>{item.prompt}</MathText></h3>{item.format==='mcq'?<div className="mt-4 grid gap-2">{item.options?.map((o,i)=><button key={i} disabled={!!result} className={`${button} text-left ${choice===i?'border-blue-600 bg-blue-50':''}`} onClick={()=>setChoice(i)}><MathText>{o}</MathText></button>)}</div>:<input aria-label="現在地テストの数値回答" className="mt-4 w-full rounded-xl border p-3" value={answer} onChange={e=>setAnswer(e.target.value)} disabled={!!result}/>}{!result?<div className="mt-4 flex gap-3"><button className={button} disabled={item.format==='mcq'?choice===null:parseNumeric(answer)===undefined} onClick={()=>submit()}>テストに回答</button><button className={button} onClick={()=>submit(true)}>わからない</button></div>:<div className="mt-4 text-sm leading-7"><strong>{result==='correct'?'正解':'復習が必要です'}</strong><p><MathText>{item.explanation}</MathText></p><div className="mt-3 flex flex-wrap gap-3"><button className={button} onClick={onNext}>次のテスト問題</button>{result!=='correct'&&<button className={button} onClick={()=>onOpen(`eng-${item.skillId}`)}>このスキルを復習する</button>}</div></div>}</section>;
}
function BankPlacement({onOpen}:{onOpen:(id:string)=>void}){
  const [records,setRecords]=useState<BankRecords>({}),[loaded,setLoaded]=useState(false),[error,setError]=useState('');
  const [group,setGroup]=useState('all'),[topic,setTopic]=useState('all'),[retest,setRetest]=useState(false);
  const [ids,setIds]=useState<string[]|null>(null),[index,setIndex]=useState(0);
  useEffect(()=>{loadBankRecords().then(r=>{setRecords(r);setLoaded(true);}).catch(()=>setError('記録を読み込めません。再読み込みしてください。'));},[]);
  const progress=bankProgress(records),list=topics.filter(t=>(group==='all'||t.group===group)&&(topic==='all'||t.id===topic));
  const start=()=>{const selected=list.filter(t=>retest||!progress[t.id].testPassed).slice(0,3);const set=selected.flatMap(t=>bankPlacementItems(t,records,retest));setIds(set);setIndex(0);};
  const current=ids?getQuestion(ids[index]??''):undefined;
  const save=async(id:string,answer:string,skip:boolean)=>{const q=getQuestion(id)!;const r=nextBankRecord(q,records[id],{answer,correction:skip?'現在地テストで未解決':'',usedHint:false,mode:'placement',now:Date.now(),skipped:skip});await saveBankRecord(r);setRecords(old=>({...old,[id]:r}));};
  if(!loaded)return <p role="status">{error||'テストの記録を読み込んでいます…'}</p>;
  return <div className="space-y-4"><section className="panel p-5"><p className="text-sm leading-7">1単元4問（2つの問題型を各2問）で確認します。全問正解ならその場でノードが埋まり、教材を飛ばして先へ進めます。後で誤答した問題型だけ再確認となります。未受験の前提単元を一括で合格にはしません。</p>{!ids&&<><div className="mt-4 flex flex-wrap gap-3"><select aria-label="単元テストの分野" value={group} onChange={e=>{setGroup(e.target.value);setTopic('all');}} className="max-w-full rounded-xl border p-3"><option value="all">全分野</option>{Object.entries(courseGroups).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select><select aria-label="単元テストの対象" value={topic} onChange={e=>setTopic(e.target.value)} className="max-w-full rounded-xl border p-3"><option value="all">未確認から最大3単元（12問）</option>{topics.filter(t=>group==='all'||t.group===group).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></div><label className="mt-3 block text-sm"><input type="checkbox" checked={retest} onChange={e=>setRetest(e.target.checked)}/> 合格済みも再テストする</label><button className={`${button} mt-4 bg-[#0d1833] text-white`} onClick={start}>単元の現在地テストを始める</button></>}</section>
    {ids&&(current?<BankTestQuestion key={`${index}-${current.id}`} id={current.id} save={save} onNext={()=>setIndex(i=>i+1)} onOpen={onOpen}/>:<section className="panel p-5"><h3 className="font-bold">{ids.length?'単元ノードへ結果を反映しました。':'今受けられる確認問題がありません。別の単元を選ぶか、6時間後に再テストできます。'}</h3><button className={`${button} mt-3`} onClick={()=>setIds(null)}>別の単元をテストする</button></section>)}{ids&&current&&<button className={button} onClick={()=>setIds(null)}>中断する（結果は保存済み）</button>}
    <div className="grid gap-3 md:grid-cols-3">{list.map(t=>{const p=progress[t.id];return <button key={t.id} onClick={()=>onOpen(t.id)} className={`rounded-xl border p-4 text-left ${p.testPassed?'border-green-500 bg-green-50':p.needsReview?'border-amber-400 bg-amber-50':'bg-white'}`}><div className="text-sm font-bold">{p.testPassed?'✓ ':''}{t.title}</div><div className="mt-2 text-xs">{p.score}% · {p.testPassed?'テスト合格・先へ進めます':p.needsReview?'再確認が必要':'未確認・確認中'}</div><div className="mt-1 text-xs text-[#657083]">時間を空けた定着：{p.retainedReady?'確認済み':'未確認'}</div></button>})}</div>
  </div>;
}
function BankTestQuestion({id,save,onNext,onOpen}:{id:string;save:(id:string,answer:string,skip:boolean)=>Promise<void>;onNext:()=>void;onOpen:(id:string)=>void}){
  const q=getQuestion(id)!;const [answer,setAnswer]=useState(''),[result,setResult]=useState<boolean|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const locked=useRef(false);
  const submit=async(skip=false)=>{if(locked.current||result!==null)return;locked.current=true;setBusy(true);setError('');try{await save(id,skip?'わからない':answer,skip);setResult(!skip&&gradeNumeric(q,answer));}catch{setError('結果を保存できませんでした。再試行してください。');}finally{locked.current=false;setBusy(false);}};
  return <section className="panel p-6"><div className="kicker">{topics.find(t=>t.id===q.topicId)?.title}</div><h3 className="mt-3 font-bold leading-8"><MathText>{q.prompt}</MathText></h3><p className="mt-2 text-xs">単位：{q.unit||'指定なし'}。整数は丸めず、小数は有効数字6桁以上。分数でも回答できます。</p><input aria-label="単元テストの回答" disabled={busy||result!==null} className="mt-4 w-full rounded-xl border p-3" value={answer} onChange={e=>setAnswer(e.target.value)}/>{result===null?<div className="mt-3 flex gap-3"><button className={button} disabled={busy||parseNumeric(answer)===undefined} onClick={()=>void submit()}>単元テストに回答</button><button className={button} disabled={busy} onClick={()=>void submit(true)}>この問題はわからない</button></div>:<div className="mt-4 text-sm leading-7"><strong>{result?'正解':'この問題型を再確認しましょう'}</strong><p>答え：{fmt(q.answer)} {q.unit}</p><p><MathText>{q.explanation}</MathText></p><div className="mt-3 flex flex-wrap gap-3"><button className={button} onClick={onNext}>次の単元テスト問題</button>{!result&&<button className={button} onClick={()=>onOpen(q.topicId)}>前提診断・基礎ドリルへ</button>}</div></div>}{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}</section>;
}
