'use client';
import { Text, tr } from './Text';

import { MathText } from './MathText';
import { useEffect, useRef, useState } from 'react';
import { skills, domainNames } from '@/data/curriculum';
import { assessments } from '@/data/assessments';
import { topics, courseGroups, getQuestion } from '@/data/foundations';
import { fmt } from '@/data/foundations/types';
import { useMasteryStore } from '@/lib/store';
import { skillStatus, defaultState } from '@/lib/mastery';
import { placementEvidence, skillTestItems } from '@/lib/placement';
import { bankProgress, bankPlacementItems, nextBankRecord, parseNumeric, gradeNumeric, type BankRecords } from '@/lib/problem-bank';
import { loadBankRecords, saveBankRecord } from '@/lib/problem-bank-db';
import type { AssessmentItem } from '@/lib/types';

const button='rounded-xl border px-4 py-3 text-sm font-semibold disabled:opacity-30';
export function PlacementTests({onOpenLesson,onOpenFoundation}:{onOpenLesson:(id:string)=>void;onOpenFoundation:(id:string)=>void}){
  const [tab,setTab]=useState<'skills'|'foundations'>('foundations');
  return <div className="space-y-5"><section className="panel p-6"><h2 className="text-xl font-bold"><Text>{"できるところは、テストで飛ばす"}</Text></h2><p className="mt-3 text-sm leading-7"><Text>{"最初から教材を読む必要はありません。分野や単元を選んで確認し、合格したノードを埋めます。後の誤答は該当箇所を再確認に戻します。時間を空けた定着確認は別に続けられます。"}</Text></p><div className="mt-4 flex flex-wrap gap-2"><button className={button} aria-pressed={tab==='foundations'} onClick={()=>setTab('foundations')}><Text>{"数学・力学など100単元"}</Text></button><button className={button} aria-pressed={tab==='skills'} onClick={()=>setTab('skills')}><Text>{"FRC・工学78スキル"}</Text></button></div></section>{tab==='foundations'?<BankPlacement onOpen={onOpenFoundation}/>:<SkillPlacement onOpen={onOpenLesson}/>}</div>;
}
function SkillPlacement({onOpen}:{onOpen:(id:string)=>void}){
  const {states,assessmentHistory}=useMasteryStore();
  const [domain,setDomain]=useState('all'),[skill,setSkill]=useState('all'),[retest,setRetest]=useState(false);
  const [ids,setIds]=useState<string[]|null>(null),[index,setIndex]=useState(0);
  const list=skills.filter(s=>(domain==='all'||s.domain===domain)&&(skill==='all'||s.id===skill));
  const start=()=>{const chosen=list.filter(s=>retest||skillStatus(states[s.id]??defaultState())!=='mastered').slice(0,3);setIds(chosen.flatMap(s=>skillTestItems(s.id,assessmentHistory,retest).map(q=>q.id)));setIndex(0);};
  const item=assessments.find(a=>a.id===ids?.[index]);
  return <div className="space-y-4"><section className="panel p-5"><p className="text-sm leading-7"><Text>{"各スキルで異なる4問・2種類以上の能力を確認します。合格するとスキルマップが埋まり、スコアは90以上になります。誤答・「わからない」はテスト合格を取り消し、達成度を75以下へ戻します。実践課題の提出は別です。"}</Text></p>
    {!ids&&<><div className="mt-4 flex flex-wrap gap-3"><select aria-label={tr("スキルテストの分野")} value={domain} onChange={e=>{setDomain(e.target.value);setSkill('all');}} className="max-w-full rounded-xl border p-3"><option value="all">{tr("全分野")}</option>{Object.entries(domainNames).map(([id,n])=><option key={id} value={id}><Text plain>{n}</Text></option>)}</select><select aria-label={tr("スキルテストの対象")} value={skill} onChange={e=>setSkill(e.target.value)} className="max-w-full rounded-xl border p-3"><option value="all">{tr("未確認から最大3スキル")}</option>{skills.filter(s=>domain==='all'||s.domain===domain).map(s=><option key={s.id} value={s.id}><Text plain>{s.nameJa}</Text></option>)}</select></div><label className="mt-3 block text-sm"><input type="checkbox" checked={retest} onChange={e=>setRetest(e.target.checked)}/><Text>{" 合格済みも再テストする"}</Text></label><button className={`${button} mt-4 bg-[#0d1833] text-white`} onClick={start}><Text>{"現在地テストを始める"}</Text></button></>}
  </section>{ids&&(item?<SkillQuestion key={`${index}-${item.id}`} item={item} onNext={()=>setIndex(i=>i+1)} onOpen={onOpen}/>:<section className="panel p-5"><h3 className="font-bold"><Text>{ids.length?'テスト結果を反映しました。':'対象の未確認問題がありません。'}</Text></h3><p className="mt-2 text-sm"><Text>{"合格済みの再テストや別の分野を選べます。"}</Text></p><button className={`${button} mt-3`} onClick={()=>setIds(null)}><Text>{"対象を選び直す"}</Text></button></section>)}
  {ids&&item&&<button className={button} onClick={()=>setIds(null)}><Text>{"中断する（回答済みの結果は保存）"}</Text></button>}
  <div className="grid gap-3 md:grid-cols-3">{list.map(s=>{const st=states[s.id]??defaultState(),passed=skillStatus(st)==='mastered',ev=placementEvidence(s.id,assessmentHistory);return <section key={s.id} className={`rounded-xl border p-4 ${passed?'border-green-500 bg-green-50':'bg-white'}`}><h3 className="font-bold text-sm"><Text>{passed?'✓ ':''}</Text><Text>{s.nameJa}</Text></h3><p className="mt-2 text-xs"><Text>{Math.round(st.score)}</Text>% · <Text>{st.testPassed?'テストで確認済み':passed?'定着確認済み':'確認中'}</Text><Text>{" · 異なる正答 "}</Text><Text>{Math.min(ev.count,4)}</Text>/4</p><button className="mt-3 text-xs text-[#0857a2]" onClick={()=>onOpen(`eng-${s.id}`)}><Text>{"必要な教材へ"}</Text></button></section>})}</div></div>;
}
function SkillQuestion({item,onNext,onOpen}:{item:AssessmentItem;onNext:()=>void;onOpen:(id:string)=>void}){
  const answerAssessment=useMasteryStore(s=>s.answerAssessment);
  const [choice,setChoice]=useState<number|null>(null),[answer,setAnswer]=useState(''),[result,setResult]=useState<string|null>(null);
  const locked=useRef(false);
  const submit=(skip=false)=>{if(locked.current)return;locked.current=true;const n=parseNumeric(answer);const correct=item.format==='mcq'?choice===item.answer:n!==undefined&&Math.abs(n-Number(item.answer))<=(item.tolerance??0);const outcome=skip?'skipped':correct?'correct':'wrong';answerAssessment(item,outcome,'placement',{selectedAnswer:item.format==='mcq'?choice??undefined:answer});setResult(outcome);};
  return <section className="panel p-6"><div className="kicker"><Text>{skills.find(s=>s.id===item.skillId)?.nameJa}</Text> · L<Text>{item.difficulty}</Text> · <Text>{item.competency}</Text></div><h3 className="mt-3 font-bold leading-8"><MathText>{item.prompt}</MathText></h3>{item.format==='mcq'?<div className="mt-4 grid gap-2">{item.options?.map((o,i)=><button key={i} disabled={!!result} className={`${button} text-left ${choice===i?'border-blue-600 bg-blue-50':''}`} onClick={()=>setChoice(i)}><MathText>{o}</MathText></button>)}</div>:<input aria-label={tr("現在地テストの数値回答")} className="mt-4 w-full rounded-xl border p-3" value={answer} onChange={e=>setAnswer(e.target.value)} disabled={!!result}/>}{!result?<div className="mt-4 flex gap-3"><button className={button} disabled={item.format==='mcq'?choice===null:parseNumeric(answer)===undefined} onClick={()=>submit()}><Text>{"テストに回答"}</Text></button><button className={button} onClick={()=>submit(true)}><Text>{"わからない"}</Text></button></div>:<div className="mt-4 text-sm leading-7"><strong><Text>{result==='correct'?'正解':'復習が必要です'}</Text></strong><p><MathText>{item.explanation}</MathText></p><div className="mt-3 flex flex-wrap gap-3"><button className={button} onClick={onNext}><Text>{"次のテスト問題"}</Text></button>{result!=='correct'&&<button className={button} onClick={()=>onOpen(`eng-${item.skillId}`)}><Text>{"このスキルを復習する"}</Text></button>}</div></div>}</section>;
}
function BankPlacement({onOpen}:{onOpen:(id:string)=>void}){
  const [records,setRecords]=useState<BankRecords>({}),[loaded,setLoaded]=useState(false),[error,setError]=useState('');
  const [group,setGroup]=useState('all'),[topic,setTopic]=useState('all'),[retest,setRetest]=useState(false);
  const [ids,setIds]=useState<string[]|null>(null),[index,setIndex]=useState(0);
  useEffect(()=>{loadBankRecords().then(r=>{setRecords(r);setLoaded(true);}).catch(()=>setError('記録を読み込めません。再読み込みしてください。'));},[]);
  const progress=bankProgress(records),list=topics.filter(t=>(group==='all'||t.group===group)&&(topic==='all'||t.id===topic));
  const start=()=>{const selected=list.filter(t=>retest||!progress[t.id].testPassed).slice(0,3);const set=selected.flatMap(t=>bankPlacementItems(t,records,retest));setIds(set);setIndex(0);};
  const current=ids?getQuestion(ids[index]??''):undefined;
  const save=async(id:string,answer:string,skip:boolean)=>{const q=getQuestion(id)!;const r=nextBankRecord(q,records[id],{answer,correction:skip?'現在地テストで未解決':'',usedHint:false,mode:'placement',now:Date.now(),skipped:skip});await saveBankRecord(r);setRecords(old=>({...old,[id]:r}));};
  if(!loaded)return <p role="status"><Text>{error||'テストの記録を読み込んでいます…'}</Text></p>;
  return <div className="space-y-4"><section className="panel p-5"><p className="text-sm leading-7"><Text>{"1単元4問（2つの問題型を各2問）で確認します。全問正解ならその場でノードが埋まり、教材を飛ばして先へ進めます。後で誤答した問題型だけ再確認となります。未受験の前提単元を一括で合格にはしません。"}</Text></p>{!ids&&<><div className="mt-4 flex flex-wrap gap-3"><select aria-label={tr("単元テストの分野")} value={group} onChange={e=>{setGroup(e.target.value);setTopic('all');}} className="max-w-full rounded-xl border p-3"><option value="all">{tr("全分野")}</option>{Object.entries(courseGroups).map(([id,n])=><option key={id} value={id}><Text plain>{n}</Text></option>)}</select><select aria-label={tr("単元テストの対象")} value={topic} onChange={e=>setTopic(e.target.value)} className="max-w-full rounded-xl border p-3"><option value="all">{tr("未確認から最大3単元（12問）")}</option>{topics.filter(t=>group==='all'||t.group===group).map(t=><option key={t.id} value={t.id}><Text plain>{t.title}</Text></option>)}</select></div><label className="mt-3 block text-sm"><input type="checkbox" checked={retest} onChange={e=>setRetest(e.target.checked)}/><Text>{" 合格済みも再テストする"}</Text></label><button className={`${button} mt-4 bg-[#0d1833] text-white`} onClick={start}><Text>{"単元の現在地テストを始める"}</Text></button></>}</section>
    {ids&&(current?<BankTestQuestion key={`${index}-${current.id}`} id={current.id} save={save} onNext={()=>setIndex(i=>i+1)} onOpen={onOpen}/>:<section className="panel p-5"><h3 className="font-bold"><Text>{ids.length?'単元ノードへ結果を反映しました。':'今受けられる確認問題がありません。別の単元を選ぶか、6時間後に再テストできます。'}</Text></h3><button className={`${button} mt-3`} onClick={()=>setIds(null)}><Text>{"別の単元をテストする"}</Text></button></section>)}{ids&&current&&<button className={button} onClick={()=>setIds(null)}><Text>{"中断する（結果は保存済み）"}</Text></button>}
    <div className="grid gap-3 md:grid-cols-3">{list.map(t=>{const p=progress[t.id];return <button key={t.id} onClick={()=>onOpen(t.id)} className={`rounded-xl border p-4 text-left ${p.testPassed?'border-green-500 bg-green-50':p.needsReview?'border-amber-400 bg-amber-50':'bg-white'}`}><div className="text-sm font-bold"><Text>{p.testPassed?'✓ ':''}</Text><Text>{t.title}</Text></div><div className="mt-2 text-xs"><Text>{p.score}</Text>% · <Text>{p.testPassed?'テスト合格・先へ進めます':p.needsReview?'再確認が必要':'未確認・確認中'}</Text></div><div className="mt-1 text-xs text-[#657083]"><Text>{"時間を空けた定着："}</Text><Text>{p.retainedReady?'確認済み':'未確認'}</Text></div></button>})}</div>
  </div>;
}
function BankTestQuestion({id,save,onNext,onOpen}:{id:string;save:(id:string,answer:string,skip:boolean)=>Promise<void>;onNext:()=>void;onOpen:(id:string)=>void}){
  const q=getQuestion(id)!;const [answer,setAnswer]=useState(''),[result,setResult]=useState<boolean|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const locked=useRef(false);
  const submit=async(skip=false)=>{if(locked.current||result!==null)return;locked.current=true;setBusy(true);setError('');try{await save(id,skip?'わからない':answer,skip);setResult(!skip&&gradeNumeric(q,answer));}catch{setError('結果を保存できませんでした。再試行してください。');}finally{locked.current=false;setBusy(false);}};
  return <section className="panel p-6"><div className="kicker"><Text>{topics.find(t=>t.id===q.topicId)?.title}</Text></div><h3 className="mt-3 font-bold leading-8"><MathText>{q.prompt}</MathText></h3><p className="mt-2 text-xs"><Text>{"単位："}</Text><Text>{q.unit||'指定なし'}</Text><Text>{"。整数は丸めず、小数は有効数字6桁以上。分数でも回答できます。"}</Text></p><input aria-label={tr("単元テストの回答")} disabled={busy||result!==null} className="mt-4 w-full rounded-xl border p-3" value={answer} onChange={e=>setAnswer(e.target.value)}/>{result===null?<div className="mt-3 flex gap-3"><button className={button} disabled={busy||parseNumeric(answer)===undefined} onClick={()=>void submit()}><Text>{"単元テストに回答"}</Text></button><button className={button} disabled={busy} onClick={()=>void submit(true)}><Text>{"この問題はわからない"}</Text></button></div>:<div className="mt-4 text-sm leading-7"><strong><Text>{result?'正解':'この問題型を再確認しましょう'}</Text></strong><p><Text>{"答え："}</Text><Text>{fmt(q.answer)}</Text> <Text>{q.unit}</Text></p><p><MathText>{q.explanation}</MathText></p><div className="mt-3 flex flex-wrap gap-3"><button className={button} onClick={onNext}><Text>{"次の単元テスト問題"}</Text></button>{!result&&<button className={button} onClick={()=>onOpen(q.topicId)}><Text>{"前提診断・基礎ドリルへ"}</Text></button>}</div></div>}{error&&<p role="alert" className="mt-3 text-red-700"><Text>{error}</Text></p>}</section>;
}
